"""Added new user table

Revision ID: 034403df6769
Revises: 94943dc041a0
Create Date: 2024-03-07 19:36:01.354342

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "034403df6769"
down_revision: str | None = "94943dc041a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("hashed_password", sa.String(), nullable=False))
    op.add_column("user", sa.Column("is_verified", sa.Boolean(), nullable=False))
    op.alter_column(
        "user",
        "full_name",
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
    )
    op.alter_column("user", "weight", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "weight", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "user",
        "full_name",
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
    )
    op.drop_column("user", "is_verified")
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###
